// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWYLisans.Persistence.Context;

#nullable disable

namespace TWYLisans.Persistence.Migrations
{
    [DbContext(typeof(TWYLisansDbContext))]
    partial class TWYLisansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWYLisans.Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            categoryName = "A kategorisi"
                        },
                        new
                        {
                            ID = 2,
                            categoryName = "B kategorisi"
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("cityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            cityname = "Ankara"
                        },
                        new
                        {
                            ID = 2,
                            cityname = "Bursa"
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ePosta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("townId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("townId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            active = true,
                            companyName = "A şirketi",
                            ePosta = "aaa@aaa.aaa",
                            phoneNumber = "00220202101",
                            townId = 1
                        },
                        new
                        {
                            ID = 2,
                            active = true,
                            companyName = "B şirketi",
                            ePosta = "bbb@bbb.bbb",
                            phoneNumber = "22202020202",
                            townId = 2
                        },
                        new
                        {
                            ID = 3,
                            active = true,
                            companyName = "C şirketi",
                            ePosta = "ccc@ccc.ccc",
                            phoneNumber = "30303030303",
                            townId = 3
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Licence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("endingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("licencekey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("customerId");

                    b.HasIndex("productId");

                    b.ToTable("Licences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            active = true,
                            creationDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3971),
                            customerId = 1,
                            endingDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3983),
                            licencekey = new Guid("5c8ad19b-e355-49f5-bfa8-e215ced42baa"),
                            productId = 1
                        },
                        new
                        {
                            ID = 2,
                            active = true,
                            creationDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3985),
                            customerId = 2,
                            endingDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3986),
                            licencekey = new Guid("21f4935e-8ffa-47dd-8ed8-45d19c746456"),
                            productId = 2
                        },
                        new
                        {
                            ID = 3,
                            active = true,
                            creationDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3987),
                            customerId = 2,
                            endingDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3988),
                            licencekey = new Guid("ffe1b770-2303-4bc2-b233-3cea214024b5"),
                            productId = 1
                        },
                        new
                        {
                            ID = 4,
                            active = true,
                            creationDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3989),
                            customerId = 3,
                            endingDate = new DateTime(2023, 7, 25, 17, 31, 36, 685, DateTimeKind.Local).AddTicks(3990),
                            licencekey = new Guid("60b88584-a01f-4c65-a327-c8fd259b0e60"),
                            productId = 2
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            active = true,
                            categoryId = 1,
                            productDescription = "A açıklaması",
                            productName = "A Ürünü"
                        },
                        new
                        {
                            ID = 2,
                            active = true,
                            categoryId = 2,
                            productDescription = "B açıklaması",
                            productName = "B Ürünü"
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Town", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("cityId")
                        .HasColumnType("int");

                    b.Property<string>("townname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("cityId");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            cityId = 1,
                            townname = "Çankaya"
                        },
                        new
                        {
                            ID = 2,
                            cityId = 1,
                            townname = "Haymana"
                        },
                        new
                        {
                            ID = 3,
                            cityId = 2,
                            townname = "Nilüfer"
                        });
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Customer", b =>
                {
                    b.HasOne("TWYLisans.Domain.Entities.Town", "town")
                        .WithMany("customers")
                        .HasForeignKey("townId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("town");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Licence", b =>
                {
                    b.HasOne("TWYLisans.Domain.Entities.Customer", "customer")
                        .WithMany("licences")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TWYLisans.Domain.Entities.Product", "product")
                        .WithMany("licences")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Product", b =>
                {
                    b.HasOne("TWYLisans.Domain.Entities.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Town", b =>
                {
                    b.HasOne("TWYLisans.Domain.Entities.City", "city")
                        .WithMany("towns")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.City", b =>
                {
                    b.Navigation("towns");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Customer", b =>
                {
                    b.Navigation("licences");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Product", b =>
                {
                    b.Navigation("licences");
                });

            modelBuilder.Entity("TWYLisans.Domain.Entities.Town", b =>
                {
                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
